import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "./themeProvider/themeProvider";
import { SkeletonTheme } from "react-loading-skeleton";
import { DataProvider } from "@/data/data";

export const metadata: Metadata = {
  title: "Tier Creator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SkeletonTheme baseColor="var(--foreground)" highlightColor="var(--highlight)">
        <DataProvider>
          <body className={`antialiased`} >
            <ThemeProvider />
            {children}
          </body>
        </DataProvider>
      </SkeletonTheme>
    </html>
  );
}
