import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "./themeProvider/themeProvider";

export const metadata: Metadata = {
  title: "Tier Creator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`} >
        <ThemeProvider />
        {children}
      </body>
    </html>
  );
}
